### ISSUE TITLE
Error Installing

### ISSUE THREAD

**Issue by Exonical** [compactd/compactd#56]
Fresh Install, running Ubuntu 16.04
[2018-03-06T04_19_11_263Z-debug.log](https://github.com/compactd/compactd/files/1783501/2018-03-06T04_19_11_263Z-debug.log)

**Comment by vinz243** [comment]
Could you try running 
```
sudo apt-get install build-essential g++
```

Then retry npm install?

**Comment by Exonical** [comment]
Both were already installed and updated, same issue.

**Comment by vinz243** [comment]
can you try 
```
npm i -g sharp@0.16.2 --verbose
```

**Comment by Exonical** [comment]
Same error with sharp

**Comment by Exonical** [comment]
I installed a completely fresh version of Ubuntu , now when running sudo compactd --configure I get this error

```
root@music:~# sudo compactd --configure
/usr/lib/node_modules/compactd/node_modules/bindings/bindings.js:96
  throw err
Error: Could not locate the bindings file. Tried:
/usr/lib/node_modules/compactd/node_modules/level/node_modules/leveldown/build/leveldown.node
/usr/lib/node_modules/compactd/node_modules/level/node_modules/leveldown/build/Debug/leveldown.node
 → /usr/lib/node_modules/compactd/node_modules/level/node_modules/leveldown/build/Release/leveldown.node
 → /usr/lib/node_modules/compactd/node_modules/level/node_modules/leveldown/out/Debug/leveldown.node
 → /usr/lib/node_modules/compactd/node_modules/level/node_modules/leveldown/Debug/leveldown.node
 → /usr/lib/node_modules/compactd/node_modules/level/node_modules/leveldown/out/Release/leveldown.node
 → /usr/lib/node_modules/compactd/node_modules/level/node_modules/leveldown/Release/leveldown.node
 → /usr/lib/node_modules/compactd/node_modules/level/node_modules/leveldown/build/default/leveldown.node
 → /usr/lib/node_modules/compactd/node_modules/level/node_modules/leveldown/compiled/8.10.0/linux/x64/leveldown.node
    at bindings (/usr/lib/node_modules/compactd/node_modules/bindings/bindings.js:93:9)
    at Object.<anonymous> (/usr/lib/node_modules/compactd/node_modules/level/node_modules/leveldown/leveldown.js:4:46)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/lib/node_modules/compactd/node_modules/level/level.js:1:106)
```

**Comment by vinz243** [comment]
Did you get any issue with `npm install` ? looks like binaries weren't properly built

**Comment by Exonical** [comment]
No errors from that, just warnings about certain things be deprecated

**Comment by vinz243** [comment]
Looks like you have an old version of npm. Are you using node and npm binaries from apt repository?

**Comment by Exonical** [comment]
Installed from official NodeJS site, version 8 node and version 5 npm

**Comment by vinz243** [comment]
Did you first tried using nvm and then from NodeJS site?

Can you run
```
node -v
which node
npm -v
which npm
```

And write here the results?

**Comment by Exonical** [comment]
node -v
v8.10.0
npm -v
5.6.0

**Comment by vinz243** [comment]
You forget the which, anyway can you cd into compactd installation 
```
cd $(dirname $(readlink -f $(which compactd)))
npm rebuild sharp leveldown
```
And don't run compactd as sudo btw, should add a sudo-block

**Comment by Exonical** [comment]
```
root@music:~# cd $(dirname $(readlink -f $(which compactd)))
root@music:/usr/lib/node_modules/compactd# npm rebuild sharp leveldown

> leveldown@1.9.0 install /usr/lib/node_modules/compactd/node_modules/leveldown
> prebuild-install || node-gyp rebuild

prebuild-install info begin Prebuild-install version 2.5.1
prebuild-install info looking for local prebuild @ prebuilds/leveldown-v1.9.0-node-v57-linux-x64.tar.gz
prebuild-install info looking for cached prebuild @ /root/.npm/_prebuilds/https-github.com-level-leveldown-releases-download-v1.9.0-leveldown-v1.9.0-node-v57-linux-x64.tar.gz
prebuild-install http request GET https://github.com/level/leveldown/releases/download/v1.9.0/leveldown-v1.9.0-node-v57-linux-x64.tar.gz
prebuild-install http 200 https://github.com/level/leveldown/releases/download/v1.9.0/leveldown-v1.9.0-node-v57-linux-x64.tar.gz
prebuild-install info downloading to @ /root/.npm/_prebuilds/https-github.com-level-leveldown-releases-download-v1.9.0-leveldown-v1.9.0-node-v57-linux-x64.tar.gz.11775-3d4437790b43a.tmp
prebuild-install info renaming to @ /root/.npm/_prebuilds/https-github.com-level-leveldown-releases-download-v1.9.0-leveldown-v1.9.0-node-v57-linux-x64.tar.gz
prebuild-install info unpacking @ /root/.npm/_prebuilds/https-github.com-level-leveldown-releases-download-v1.9.0-leveldown-v1.9.0-node-v57-linux-x64.tar.gz
prebuild-install info unpack resolved to /usr/lib/node_modules/compactd/node_modules/leveldown/build/Release/leveldown.node
prebuild-install info unpack required /usr/lib/node_modules/compactd/node_modules/leveldown/build/Release/leveldown.node successfully
prebuild-install info install Successfully installed prebuilt binary!

> leveldown@2.1.1 install /usr/lib/node_modules/compactd/node_modules/level/node_modules/leveldown
> prebuild-install || node-gyp rebuild

prebuild-install info begin Prebuild-install version 2.5.1
prebuild-install info looking for local prebuild @ prebuilds/leveldown-v2.1.1-node-v57-linux-x64.tar.gz
prebuild-install info looking for cached prebuild @ /root/.npm/_prebuilds/https-github.com-level-leveldown-releases-download-v2.1.1-leveldown-v2.1.1-node-v57-linux-x64.tar.gz
prebuild-install http request GET https://github.com/level/leveldown/releases/download/v2.1.1/leveldown-v2.1.1-node-v57-linux-x64.tar.gz
prebuild-install http 200 https://github.com/level/leveldown/releases/download/v2.1.1/leveldown-v2.1.1-node-v57-linux-x64.tar.gz
prebuild-install info downloading to @ /root/.npm/_prebuilds/https-github.com-level-leveldown-releases-download-v2.1.1-leveldown-v2.1.1-node-v57-linux-x64.tar.gz.11787-a0c2a40365ba.tmp
prebuild-install info renaming to @ /root/.npm/_prebuilds/https-github.com-level-leveldown-releases-download-v2.1.1-leveldown-v2.1.1-node-v57-linux-x64.tar.gz
prebuild-install info unpacking @ /root/.npm/_prebuilds/https-github.com-level-leveldown-releases-download-v2.1.1-leveldown-v2.1.1-node-v57-linux-x64.tar.gz
prebuild-install info unpack resolved to /usr/lib/node_modules/compactd/node_modules/level/node_modules/leveldown/build/Release/leveldown.node
prebuild-install info unpack required /usr/lib/node_modules/compactd/node_modules/level/node_modules/leveldown/build/Release/leveldown.node successfully
prebuild-install info install Successfully installed prebuilt binary!

> leveldown@2.1.1 install /usr/lib/node_modules/compactd/node_modules/pouchdb/node_modules/leveldown
> prebuild-install || node-gyp rebuild

prebuild-install info begin Prebuild-install version 2.5.1
prebuild-install info looking for local prebuild @ prebuilds/leveldown-v2.1.1-node-v57-linux-x64.tar.gz
prebuild-install info looking for cached prebuild @ /root/.npm/_prebuilds/https-github.com-level-leveldown-releases-download-v2.1.1-leveldown-v2.1.1-node-v57-linux-x64.tar.gz
prebuild-install info found cached prebuild 
prebuild-install info unpacking @ /root/.npm/_prebuilds/https-github.com-level-leveldown-releases-download-v2.1.1-leveldown-v2.1.1-node-v57-linux-x64.tar.gz
prebuild-install info unpack resolved to /usr/lib/node_modules/compactd/node_modules/pouchdb/node_modules/leveldown/build/Release/leveldown.node
prebuild-install info unpack required /usr/lib/node_modules/compactd/node_modules/pouchdb/node_modules/leveldown/build/Release/leveldown.node successfully
prebuild-install info install Successfully installed prebuilt binary!

> sharp@0.17.3 install /usr/lib/node_modules/compactd/node_modules/sharp
> node-gyp rebuild

Traceback (most recent call last):
  File "/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 13, in <module>
    import gyp
  File "/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 8, in <module>
    import gyp.input
  File "/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 5, in <module>
    from compiler.ast import Const
ImportError: No module named compiler.ast
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.4.0-116-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/compactd/node_modules/sharp
gyp ERR! node -v v8.10.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.17.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sharp@0.17.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-03-08T14_28_47_574Z-debug.log
root@music:/usr/lib/node_modules/compactd# cat /root/.npm/_logs/2018-03-08T14_28_47_574Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'rebuild',
1 verbose cli   'sharp',
1 verbose cli   'leveldown' ]
2 info using npm@5.6.0
3 info using node@v8.10.0
4 info readInstalled object
5 verbose rebuild path, id [ '/usr/lib/node_modules/compactd/node_modules/leveldown',
5 verbose rebuild   'leveldown@1.9.0' ]
6 verbose rebuild path, id [ '/usr/lib/node_modules/compactd/node_modules/level/node_modules/leveldown',
6 verbose rebuild   'leveldown@2.1.1' ]
7 verbose rebuild path, id [ '/usr/lib/node_modules/compactd/node_modules/pouchdb/node_modules/leveldown',
7 verbose rebuild   'leveldown@2.1.1' ]
8 verbose rebuild path, id [ '/usr/lib/node_modules/compactd/node_modules/sharp',
8 verbose rebuild   'sharp@0.17.3' ]
9 verbose rebuild path, id [ '/usr/lib/node_modules/compactd/node_modules/smartcrop-sharp/node_modules/sharp',
9 verbose rebuild   'sharp@0.16.2' ]
10 silly rebuild set [ '/usr/lib/node_modules/compactd/node_modules/leveldown',
10 silly rebuild set   '/usr/lib/node_modules/compactd/node_modules/level/node_modules/leveldown',
10 silly rebuild set   '/usr/lib/node_modules/compactd/node_modules/pouchdb/node_modules/leveldown',
10 silly rebuild set   '/usr/lib/node_modules/compactd/node_modules/sharp',
10 silly rebuild set   '/usr/lib/node_modules/compactd/node_modules/smartcrop-sharp/node_modules/sharp' ]
11 info build /usr/lib/node_modules/compactd/node_modules/leveldown
12 info lifecycle leveldown@1.9.0~preinstall: leveldown@1.9.0
13 info linkStuff leveldown@1.9.0
14 silly linkStuff leveldown@1.9.0 has /usr/lib/node_modules/compactd/node_modules as its parent node_modules
15 verbose linkBins leveldown@1.9.0
16 verbose linkMans leveldown@1.9.0
17 info lifecycle leveldown@1.9.0~install: leveldown@1.9.0
18 verbose lifecycle leveldown@1.9.0~install: unsafe-perm in lifecycle false
19 verbose lifecycle leveldown@1.9.0~install: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/usr/lib/node_modules/compactd/node_modules/leveldown/node_modules/.bin:/usr/lib/node_modules/compactd/node_modules/.bin:/usr/lib/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
20 verbose lifecycle leveldown@1.9.0~install: CWD: /usr/lib/node_modules/compactd/node_modules/leveldown
21 silly lifecycle leveldown@1.9.0~install: Args: [ '-c', 'prebuild-install || node-gyp rebuild' ]
22 silly lifecycle leveldown@1.9.0~install: Returned: code: 0  signal: null
23 info lifecycle leveldown@1.9.0~postinstall: leveldown@1.9.0
24 info build /usr/lib/node_modules/compactd/node_modules/level/node_modules/leveldown
25 info lifecycle leveldown@2.1.1~preinstall: leveldown@2.1.1
26 info linkStuff leveldown@2.1.1
27 silly linkStuff leveldown@2.1.1 has /usr/lib/node_modules/compactd/node_modules/level/node_modules as its parent node_modules
28 verbose linkBins leveldown@2.1.1
29 verbose linkMans leveldown@2.1.1
30 info lifecycle leveldown@2.1.1~install: leveldown@2.1.1
31 verbose lifecycle leveldown@2.1.1~install: unsafe-perm in lifecycle false
32 verbose lifecycle leveldown@2.1.1~install: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/usr/lib/node_modules/compactd/node_modules/level/node_modules/leveldown/node_modules/.bin:/usr/lib/node_modules/compactd/node_modules/level/node_modules/.bin:/usr/lib/node_modules/compactd/node_modules/.bin:/usr/lib/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
33 verbose lifecycle leveldown@2.1.1~install: CWD: /usr/lib/node_modules/compactd/node_modules/level/node_modules/leveldown
34 silly lifecycle leveldown@2.1.1~install: Args: [ '-c', 'prebuild-install || node-gyp rebuild' ]
35 silly lifecycle leveldown@2.1.1~install: Returned: code: 0  signal: null
36 info lifecycle leveldown@2.1.1~postinstall: leveldown@2.1.1
37 info build /usr/lib/node_modules/compactd/node_modules/pouchdb/node_modules/leveldown
38 info lifecycle leveldown@2.1.1~preinstall: leveldown@2.1.1
39 info linkStuff leveldown@2.1.1
40 silly linkStuff leveldown@2.1.1 has /usr/lib/node_modules/compactd/node_modules/pouchdb/node_modules as its parent node_modules
41 verbose linkBins leveldown@2.1.1
42 verbose linkMans leveldown@2.1.1
43 info lifecycle leveldown@2.1.1~install: leveldown@2.1.1
44 verbose lifecycle leveldown@2.1.1~install: unsafe-perm in lifecycle false
45 verbose lifecycle leveldown@2.1.1~install: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/usr/lib/node_modules/compactd/node_modules/pouchdb/node_modules/leveldown/node_modules/.bin:/usr/lib/node_modules/compactd/node_modules/pouchdb/node_modules/.bin:/usr/lib/node_modules/compactd/node_modules/.bin:/usr/lib/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
46 verbose lifecycle leveldown@2.1.1~install: CWD: /usr/lib/node_modules/compactd/node_modules/pouchdb/node_modules/leveldown
47 silly lifecycle leveldown@2.1.1~install: Args: [ '-c', 'prebuild-install || node-gyp rebuild' ]
48 silly lifecycle leveldown@2.1.1~install: Returned: code: 0  signal: null
49 info lifecycle leveldown@2.1.1~postinstall: leveldown@2.1.1
50 info build /usr/lib/node_modules/compactd/node_modules/sharp
51 info lifecycle sharp@0.17.3~preinstall: sharp@0.17.3
52 info linkStuff sharp@0.17.3
53 silly linkStuff sharp@0.17.3 has /usr/lib/node_modules/compactd/node_modules as its parent node_modules
54 verbose linkBins sharp@0.17.3
55 verbose linkMans sharp@0.17.3
56 info lifecycle sharp@0.17.3~install: sharp@0.17.3
57 verbose lifecycle sharp@0.17.3~install: unsafe-perm in lifecycle false
58 verbose lifecycle sharp@0.17.3~install: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/usr/lib/node_modules/compactd/node_modules/sharp/node_modules/.bin:/usr/lib/node_modules/compactd/node_modules/.bin:/usr/lib/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
59 verbose lifecycle sharp@0.17.3~install: CWD: /usr/lib/node_modules/compactd/node_modules/sharp
60 silly lifecycle sharp@0.17.3~install: Args: [ '-c', 'node-gyp rebuild' ]
61 silly lifecycle sharp@0.17.3~install: Returned: code: 1  signal: null
62 info lifecycle sharp@0.17.3~install: Failed to exec install script
63 verbose stack Error: sharp@0.17.3 install: `node-gyp rebuild`
63 verbose stack Exit status 1
63 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
63 verbose stack     at emitTwo (events.js:126:13)
63 verbose stack     at EventEmitter.emit (events.js:214:7)
63 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
63 verbose stack     at emitTwo (events.js:126:13)
63 verbose stack     at ChildProcess.emit (events.js:214:7)
63 verbose stack     at maybeClose (internal/child_process.js:925:16)
63 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
64 verbose pkgid sharp@0.17.3
65 verbose cwd /usr/lib/node_modules/compactd
66 verbose Linux 4.4.0-116-generic
67 verbose argv "/usr/bin/node" "/usr/bin/npm" "rebuild" "sharp" "leveldown"
68 verbose node v8.10.0
69 verbose npm  v5.6.0
70 error code ELIFECYCLE
71 error errno 1
72 error sharp@0.17.3 install: `node-gyp rebuild`
72 error Exit status 1
73 error Failed at the sharp@0.17.3 install script.
73 error This is probably not a problem with npm. There is likely additional logging output above.
74 verbose exit [ 1, true ]
```
Same errors I believe.

**Comment by Exonical** [comment]
Which node
/usr/bin/node
Which npm
/usr/bin/npm

**Comment by vinz243** [comment]
Try
```
sudo apt-get install python-dev
```

**Comment by Exonical** [comment]
Reinstalled and it successfully installed, now I'm getting an error with serving the app `nginx: [emerg] open() "/etc/nginx/snippets/ssl-compactd.io.conf" failed (2: No such file or directory)` when using the config for nginx

**Comment by vinz243** [comment]
You would need to replace those lines with your own config file for SSL, because otherwise anybody would be able to see passwords https://www.digitalocean.com/community/tutorials/how-to-secure-nginx-with-let-s-encrypt-on-ubuntu-16-04

But that also requires a domain name, but it is the only way you can make sure you can connect securely to your seedbox.

**Comment by Exonical** [comment]
SSL is setup, now I'm just receiving an 502 Bad Gateway
`2018/03/09 22:44:11 [error] 2706#2706: *1 connect() failed (111: Connection refused) while connecting to upstream, client: MY.IP.REDACTED, server: music.DOMAIN.org, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:9000/", host: "music.DOMAIN.org"
`

**Comment by Exonical** [comment]
Nginx Config

```
server {
    listen 80;
    server_name music.DOMAIN.org;
    return 301 https://$server_name$request_uri;
}

server {

    listen 443 ssl;                                                             
    server_name music.DOMAIN.org;

    # SSL Configuration
    ssl_certificate /etc/letsencrypt/live/music.DOMAIN.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/music.DOMAIN.org/privkey.pem;
    ssl_session_cache shared:SSL:10m;
    ssl_protocols TLSv1.2;
    ssl_ciphers 'ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256';
    ssl_prefer_server_ciphers on;

    add_header Strict-Transport-Security "max-age=15768000; preload;";
    add_header X-Content-Type-Options nosniff;
    add_header X-XSS-Protection "1; mode=block";
    add_header X-Robots-Tag none;
    add_header Content-Security-Policy "frame-ancestors 'self'";
    add_header X-Frame-Options DENY;

    access_log            /var/log/nginx/access.log;

    location /engine.io/ {
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
      proxy_http_version 1.1;
      proxy_set_header        Host $host;
      proxy_set_header        X-Real-IP $remote_addr;
      proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header        X-Forwarded-Proto $scheme;

      proxy_pass          http://127.0.0.1:9001;
    }

    location / {
      proxy_set_header        Host $host;
      proxy_set_header        X-Real-IP $remote_addr;
      proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header        X-Forwarded-Proto $scheme;

      # Fix the âIt appears that your reverse proxy set up is broken" error.
      proxy_pass          http://127.0.0.1:9000;
      proxy_read_timeout  90;

      proxy_redirect      http://127.0.0.1:9000 https://music.DOMAIN.org;
    }
  }
```

I'm assuming it has to do with `location /engine.io/ ` if so, what should it be? I don't know what that path is for

**Comment by vinz243** [comment]
You are almost setup, you just need to run
```
pm2 start compactd-www
```

If it says pm2 cannot be found just install it

```
npm install --global pm2
```

engine.io path is used so that databases changes are replicated in realtime using websockets. Theorically it's possible without (using http) but since I'm proxying from node it doesn't work. I use a different port because I wanted another process, so that it doesnt take on compactd main app CPU usage

**Comment by Exonical** [comment]
Last error hopefully, `An error happened during database sync for artworks: undefined` after logging in and page does not fully load.

**Comment by vinz243** [comment]
Can you open DevTools (right click on the page) then in the console tab copy and paste the content (removing any personnal informations) ?

**Comment by Exonical** [comment]
```
Firefox can’t establish a connection to the server at wss://music.DOMAIN.org/socket.io/?EIO=3&transport=websocket&sid=S8wzbfHDTnsgF1MbAAAG.
application.js:78:28133
The above 404 is totally normal. PouchDB is just detecting if the remote exists.
application.js:24:46105
Object { error: "unauthorized", reason: "You are not a server admin.", status: 401, name: "unauthorized", message: "You are not a server admin.", result: {…}, stack: "" }
  t/</</<@https://music.DOMAIN.org/application.js?455225a5e8e691261539:24:375005
i.prototype.emit@https://music.DOMAIN.org/application.js?455225a5e8e691261539:78:33034
_@https://music.DOMAIN.org/application.js?455225a5e8e691261539:24:125819
s@https://music.DOMAIN.org/application.js?455225a5e8e691261539:24:125620
f/<@https://music.DOMAIN.org/application.js?455225a5e8e691261539:24:127649
application.js:24:374982
An error happened during database sync for artworks: undefined
application.js:24:166268
```

**Comment by vinz243** [comment]
In `~/.compactd/config.json`  you can find the `couchPassword` which is the admin password set up to secure couchdb. Can you run:

```
curl -v http://admin:<couchdb password value>@localhost:5984/artworks
```

Normally you should get a 200, if not

```
curl -v -X PUT http://admin:<couchdb password value>@localhost:5984/artworks
```

should "fix" it, but none of your music will have artworks for the moment. I should add an option to trigger artwork fetching to the CLI

Btw, use ` ``` ` to wrap your multiline code like this

    ```
    I'm multiline code,
    Makes it more readable than just a `
    ```

If you are posting the result of a curl, dont forget to write out the Authorization header

**Comment by Exonical** [comment]
That fixed it, artwork isn't a big issue at all. Appreciate all the help and being patient with me!
```
And thanks for the tip about multi-line code
Helps a lot ;)
```

**Comment by vinz243** [comment]
No problems happy to help and glad to see people interested! If you have any suggestion or bug report don't hesitate !
Btw did the configure command stopped prematurely? An error perhaps? The artworks database shouldn't be empty... or do you only have a few niche artists/albums and compactd was unable to find any artwork (so it wouldn't create the database)?

**Comment by Exonical** [comment]
Err I don't believe so.. I don't have that part still open sadly. Quick question, do songs only with meta data like Artist names and such work? I have a few `.mp3`'s uploaded in my music folder that aren't detected. Also I cannot add a new library from the settings page.

**Comment by Exonical** [comment]
Looks like I answered my own question with the meta data part, besides that the artworks do work by the way.

**Comment by vinz243** [comment]
After being idle for a while (ie no requests made to the server) it will try to download artworks from discogs (which takes longer than lastfm, since there is no real API). For the metadata do you mean your files don't have a title / album tag? Right now missing any of those will likely result in an error because they are required by the scanner

https://github.com/compactd/compactd/blob/2d56cd5a45d2a5abf972ff0a4856eca22d0e1f0e/server/src/features/scanner/Scanner.ts#L204-L216

but the scanner should keep running since the error is caught:

https://github.com/compactd/compactd/blob/2d56cd5a45d2a5abf972ff0a4856eca22d0e1f0e/server/src/features/scanner/Scanner.ts#L288-L290
