### ISSUE TITLE
Database sync is really slow and errors out.

### ISSUE THREAD

**Issue by almet** [compactd/compactd#63]
After adding a bunch of albums in the library, when I try to reconnect to my server, the loader takes a really long time and eventually errors out with an error similar to « An error happened during database sync for artworks ».

When I look in the console, a lot of requests are sent to what seems to be the couchdb server, and they reach the other side, but at some point requests stop to be sent and it just stays like this. I need to reload the page to get the sync going, but it seems I'm stuck there.

I'll try a few things and report my findings here.

**Comment by almet** [comment]
A few more information.

I first though that the error was coming from my NGINX configuration (as I enabled HTTP2 on the frontend), but when I run the application directly without going through a reverse proxy, the problem is still present: the requests stop flowing after ~20s.

I'm now currently reading the source code of both compactd and pouchdb to see if there is something that enforces the requests to stop after a certain amount of time.

**Comment by almet** [comment]
Still not working, I'll let it here now. I believe it's a browser-only related issue, since the Android app is behaving properly.

**Comment by almet** [comment]
It seems that the image files stop getting downloading after a while. The server doesn't seem to answer to these? Not sure why. Here is a capture of what's happening.
![capture du 2018-04-08 22-08-37](https://user-images.githubusercontent.com/67073/38472064-835d4788-3b7a-11e8-9c75-3893e8827437.png)

**Comment by vinz243** [comment]
I'm not sure why this is happening, maybe pouchdb/pouchdb#5114 might help you, especially @ theutopianster :

> Hey guys I had the same issue with running sync or replicate from puch enabled website to couch db.
I finally figured out how to fix it, at least on my side.
Basically the timeout parameter was the culprit because after I set the variable to 0 inside pouch js it worked.
So in the file puchdb-6.1.2.js method api.allDocs
I setopts.timeout = 0; and commented
('timeout' in opts) ? opts.timeout : ('timeout' in ajaxOpts) ? ajaxOpts.timeout : 30 * 1000;
I tested with 30 min, 1 hour and more and it does not die anymore.
I ran this with CouchDB 1.6.1 and 2.0 so I hope this works for you as well.

If you need help applying his instructions just ask, I'll release another version. What version of couchDB are you running btw?

**Comment by almet** [comment]
Thanks for the insights. I'm currently running Couchdb 2.2.0.

How would you do it? This probably is a different issue, but I've tried yesterday to actually do this change, and must admit that I have trouble to compile and serve the files directly from my server.

Here are the errors I'm getting:

```js
2018-04-09T07:20:30.151Z           storyboard INFO  ┌── ROOT STORY: Node.js 8.9.0 on Linux 64-bit, SB 3.1.3 [CREATED]
2018-04-09T07:20:30.154Z           storyboard INFO  Log filter: *:DEBUG
2018-04-09T07:20:35.836Z           storyboard INFO  └── ROOT STORY: Node.js 8.9.0 on Linux 64-bit, SB 3.1.3 [CLOSED]
module.js:538
    throw err;
    ^

Error: Cannot find module '../build/Release/sharp.node'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/www/compactd/compactd/node_modules/sharp/lib/constructor.js:8:15)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
```

I've run a `npm install` and `npm run build` which ran successfully. Alternatively, another release would help me check that this is still a problem.

As a side note: this might be related to my connection: I'm using a different (much quicker) connection right now and the sync went smoothly.

**Comment by vinz243** [comment]
You can run
```
npm rebuild sharp
```

To rebuild the module, should be fine then.

> As a side note: this might be related to my connection: I'm using a different (much quicker) connection right now and the sync went smoothly.

I tried to throttle connection speed using chrome dev tools and I get the same error, so it's most probably the reason. This needs to be adressed in next version

**Comment by almet** [comment]
I've made the following changes without success (still the same error).

```diff
+++ b/client/src/features/app/app.tsx
@@ -90,7 +90,7 @@ function syncDB (dbs: string[], max: number): thunk.ThunkAction<void, Defs.Compa
     const db = new PouchDB(dbName);
     const remote = getHttpDatabase(dbName);
 
-    db.replicate.from(remote).on('complete', (info) => {
+    db.replicate.from(remote, {timeout: 30*1000}).on('complete', (info) => {

```

**Comment by vinz243** [comment]
- While it would not directly fix your issue, next version (2.0.0) should let the user select if he wants to replicate (faster local access, loading takes longer) or remote access (slower but does not require a good internet)
 - Try increasing the timeout to 180 seconds, and also pass the option to the ajax object, and applying this patch:


```diff
--- a/client/src/app/database.ts
+++ b/client/src/app/database.ts
@@ -15,6 +15,7 @@ export const getHttpDatabase = function<T> (name: string) {
   return new PouchDB<T>(`${window.location.origin}/database/${name}`, {
     ajax: {
       cache: true,
+      timeout: 180*1000,
       headers: {
         Authorization: 'Bearer ' + session.getToken()
       }
```

**Comment by almet** [comment]
Applying this
```diff
diff --git a/client/src/app/database.ts b/client/src/app/database.ts
index 0f14c39..37dc2b8 100644
--- a/client/src/app/database.ts
+++ b/client/src/app/database.ts
@@ -15,6 +15,7 @@ export const getHttpDatabase = function<T> (name: string) {
   return new PouchDB<T>(`${window.location.origin}/database/${name}`, {
     ajax: {
       cache: true,
+      timeout: 180*1000,
       headers: {
         Authorization: 'Bearer ' + session.getToken()
       }
@@ -38,4 +39,4 @@ export const syncDatabases = function (...dbs: string[]) {
   return Promise.all(dbs.map((db) => {
     return getDatabase(db).then(syncDB.bind(null, new PouchDB(db)));
   }));
-}
\ No newline at end of file
+}
diff --git a/client/src/features/app/app.tsx b/client/src/features/app/app.tsx
index b0c3bf0..4e7bc9f 100644
--- a/client/src/features/app/app.tsx
+++ b/client/src/features/app/app.tsx
@@ -90,7 +90,7 @@ function syncDB (dbs: string[], max: number): thunk.ThunkAction<void, Defs.Compa
     const db = new PouchDB(dbName);
     const remote = getHttpDatabase(dbName);
 
-    db.replicate.from(remote).on('complete', (info) => {
+    db.replicate.from(remote, {timeout: 180*1000}).on('complete', (info) => {
       dispatch({
         type: UPDATE_SYNC,
         progress: (max - dbs.length + 1) / max

```
Doesn't seem to solve the issue.
